server {
    listen 80;
    server_name localhost;

    # Отдача статики (Vue/React)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Для SPA (HTML5 History Mode)
    }

    # Проксирование API-запросов к backend
    location /api {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}