CREATE TABLE IF NOT EXISTS projects
(
    project_id   BIGSERIAL PRIMARY KEY,
    project_name VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Создание таблицы subobjects
CREATE TABLE IF NOT EXISTS subobjects
(
    subobject_id    BIGSERIAL PRIMARY KEY,
    subobject_name  VARCHAR(255) NOT NULL,
    subobject_title VARCHAR(255) NOT NULL,
    project_id      BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Внешний ключ для связи с таблицей projects
    CONSTRAINT fk_subobjects_project
        FOREIGN KEY (project_id)
            REFERENCES projects (project_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);

-- Создание таблицы standards
CREATE TABLE IF NOT EXISTS standards
(
    standard_id   BIGSERIAL PRIMARY KEY,
    standard_name VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Создание таблицы works
-- Создание таблицы works с вычисляемым столбцом
CREATE TABLE IF NOT EXISTS works
(
    work_id           BIGSERIAL PRIMARY KEY,
    work_name         VARCHAR(255) NOT NULL,
    work_units        VARCHAR(50)  NOT NULL,
    work_quantity     NUMERIC(19, 4),
    work_done         NUMERIC(19, 4),

    -- Вычисляемый столбец (PostgreSQL 12+)
    final_quantity    NUMERIC(19, 4) GENERATED ALWAYS AS (
        CASE
            WHEN work_quantity IS NULL THEN NULL
            WHEN work_done IS NULL THEN work_quantity
            ELSE work_quantity - work_done
            END
        ) STORED,

    work_standard     BIGINT,
    work_subobject_id BIGINT       NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Внешние ключи
    CONSTRAINT fk_works_standard
        FOREIGN KEY (work_standard)
            REFERENCES standards (standard_id)
            ON DELETE SET NULL
            ON UPDATE CASCADE,

    CONSTRAINT fk_works_subobject
        FOREIGN KEY (work_subobject_id)
            REFERENCES subobjects (subobject_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

    -- Проверки данных
    CONSTRAINT chk_works_quantity_positive
        CHECK (work_quantity IS NULL OR work_quantity >= 0),

    CONSTRAINT chk_works_done_positive
        CHECK (work_done IS NULL OR work_done >= 0),

    CONSTRAINT chk_works_done_not_exceed_quantity
        CHECK (work_done IS NULL OR work_quantity IS NULL OR work_done <= work_quantity)
);

CREATE TABLE IF NOT EXISTS certificates
(
    certificate_id   BIGSERIAL PRIMARY KEY,
    certificate_path VARCHAR(512) NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Создание таблицы materials
CREATE TABLE IF NOT EXISTS materials
(
    material_id        BIGSERIAL PRIMARY KEY,
    material_name      VARCHAR(255) NOT NULL,
    material_units     VARCHAR(50)  NOT NULL,
    material_documents VARCHAR(255) NOT NULL,
    author             VARCHAR(100) NOT NULL,
    number_of_pages    INTEGER      NOT NULL,
    material_standard  VARCHAR(100),
    certificate_id     BIGINT UNIQUE,
    created_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Внешний ключ для связи OneToOne с certificates (обратная сторона)
    CONSTRAINT fk_materials_certificate
        FOREIGN KEY (certificate_id)
            REFERENCES certificates (certificate_id)
            ON DELETE SET NULL
            ON UPDATE CASCADE
);

-- Создание таблицы executive_schemas
CREATE TABLE IF NOT EXISTS executive_schemas
(
    schema_id     BIGSERIAL PRIMARY KEY,
    schema_number VARCHAR(100) NOT NULL,
    schema_path   VARCHAR(512),
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Создание таблицы acts
CREATE TABLE IF NOT EXISTS acts
(
    act_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    act_project_id      INTEGER        NOT NULL,
    act_subobject_id    INTEGER        NOT NULL,
    act_works           TEXT           NOT NULL,
    act_number          VARCHAR(100)   NOT NULL,
    start_date          DATE           NOT NULL,
    end_date            DATE           NOT NULL,
    act_materials       TEXT,
    submitted_documents TEXT,
    in_accord_with      TEXT           NOT NULL,
    act_next_works      TEXT,
    act_work_done       NUMERIC(19, 2) NOT NULL,
    in_registry         VARCHAR(255),
    executive_schema_id INTEGER UNIQUE,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Внешний ключ для связи с projects
    CONSTRAINT fk_acts_project
        FOREIGN KEY (act_project_id)
            REFERENCES projects (project_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

    -- Внешний ключ для связи с subobjects
    CONSTRAINT fk_acts_subobject
        FOREIGN KEY (act_subobject_id)
            REFERENCES subobjects (subobject_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

    -- Внешний ключ для OneToOne связи с executive_schemas
    CONSTRAINT fk_acts_executive_schema
        FOREIGN KEY (executive_schema_id)
            REFERENCES executive_schemas (schema_id)
            ON DELETE SET NULL
            ON UPDATE CASCADE,

    -- Проверка дат
    CONSTRAINT chk_acts_dates_valid
        CHECK (end_date >= start_date),

    -- Проверка процента выполнения
    CONSTRAINT chk_acts_work_done_valid
        CHECK (act_work_done >= 0 AND act_work_done <= 100)
);

-- Создание таблицы entrance_controls
CREATE TABLE IF NOT EXISTS entrance_controls
(
    control_id              BIGSERIAL PRIMARY KEY,
    control_project_id      BIGINT NOT NULL,
    control_subobject_name  VARCHAR(255),
    control_number          VARCHAR(100),
    control_date            DATE,
    control_materials       TEXT,
    control_documents       TEXT,
    control_document_author VARCHAR(100),
    control_standard        VARCHAR(100),
    control_act_id          BIGINT,
    control_sheet_numbers   INTEGER,
    material_id             BIGINT UNIQUE,
    created_at              TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Внешний ключ для связи с projects
    CONSTRAINT fk_entrance_controls_project
        FOREIGN KEY (control_project_id)
            REFERENCES projects (project_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

    -- Внешний ключ для связи с acts
    CONSTRAINT fk_entrance_controls_act
        FOREIGN KEY (control_act_id)
            REFERENCES acts (act_id)
            ON DELETE SET NULL
            ON UPDATE CASCADE,

    -- Внешний ключ для OneToOne связи с materials
    CONSTRAINT fk_entrance_controls_material
        FOREIGN KEY (material_id)
            REFERENCES materials (material_id)
            ON DELETE SET NULL
            ON UPDATE CASCADE
);

-- Создание таблицы registries
CREATE TABLE IF NOT EXISTS registries
(
    registry_id         BIGSERIAL PRIMARY KEY,
    registry_row_number BIGINT,
    registry_month_id   INTEGER,
    document_name       VARCHAR(255) NOT NULL,
    document_date       DATE         NOT NULL,
    document_number     VARCHAR(255) NOT NULL,
    document_author     VARCHAR(255) NOT NULL,
    number_of_sheets    INTEGER      NOT NULL,
    list_in_order       INTEGER,
    adding_time         TIMESTAMP,
    current_act_id      BIGINT,
    CONSTRAINT fk_registry_act FOREIGN KEY (current_act_id) REFERENCES acts (act_id) ON DELETE SET NULL
);

-- Создание таблицы worklogs
CREATE TABLE IF NOT EXISTS worklogs
(
    work_log_id     BIGSERIAL PRIMARY KEY,
    work_log_date   DATE         NOT NULL,
    work_log_name   VARCHAR(255) NOT NULL,
    work_log_number INTEGER      NOT NULL
);


