# ===============================
# DATABASE CONFIGURATION
# ===============================
server.port=8080

spring.sql.init.mode=always

spring.datasource.url=jdbc:postgresql://localhost:5432/exec_doc_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.jpa.properties.hibernate.jdbc.timeout=300
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.open-in-view=false

app.storage.base-url=http://storage:80
file.upload-dir=/usr/share/nginx/html/pdf
app.storage.public-url=http://localhost:9000

app.jwt-secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt-expiration-milliseconds=604800000