# ===============================
# DATABASE CONFIGURATION
# ===============================
server.port=8080
spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:5432/exec_doc_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.jpa.properties.hibernate.jdbc.timeout=300

spring.jpa.properties.hibernate.hbm2ddl.auto=none
app.storage.base-url=http://storage:80
file.upload-dir=/usr/share/nginx/html/pdf
app.storage.public-url=http://localhost:9000